/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package playlang;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
	Arrays.stream(args).forEach(System.out::println);
    }
}
